### ISSUE TITLE
可能可以加入的內容整理

### ISSUE THREAD

**Issue by poweihuang17** [cnrv/home#10]
LLVM progress
gdbserver?
QEMU RISC-V decoding?
B group重啟？
Machine readable spec for risc-v?
jacob 送了draft 4....？若我有空看的話，會把它加上去。

**Comment by poweihuang17** [comment]
又多了個newlib/libm/libgloss patch可以加。

**Comment by wsong83** [comment]
需要修改的内容：

- @xfguo 你要不要在群里问问谁要不要发招聘广告？
- 修改License为CC BY-NC-SA
- 去掉本次空白的栏目

**Comment by poweihuang17** [comment]
Linux port v7出來了，明天一起加。

**Comment by poweihuang17** [comment]
仔細看完了LLVM的thread發現講的是沒進展....

**Comment by wsong83** [comment]
yeah, that is what I thought of.

**Comment by poweihuang17** [comment]
剛剛把我的部分加完了，把B group, linux port, libm的加入了新聞。剩下的除了QEMU的討論以外，加的價值不大。它主要是想改decoding寫法讓客製化的指令容易被加入，如果要加的話應該是加在技術討論，但考量這次技術討論內容已經太多，就留待以後缺東西時再加吧。

**Comment by wsong83** [comment]
explicit cache operation写的有点多。可以把英文quote去掉。你觉得呢？

**Comment by poweihuang17** [comment]
我覺得可以只留連結就好，畢竟已經寫的很深入了～

**Comment by wsong83** [comment]
done

**Comment by poweihuang17** [comment]
Cool, 不過剛剛又看到那個floating point的spec更動。
我真的想找一個floating point的專家教教我這些

**Comment by poweihuang17** [comment]
floating point真的複雜的超出我的意外....

**Comment by wsong83** [comment]
Me too. 完全超出我的理解范围，表示很想懂但是无能为力

**Comment by xfguo** [comment]
我们直接问两位打算写FPU部分的同学，让他们给出评论不就好了？

**Comment by wsong83** [comment]
好啊

**Comment by poweihuang17** [comment]
恩恩好啊。我下次也問問看Nhon Quach。他是floating point的專家。我真的從他那邊搞懂了，能幫得上忙的話再幫忙評論～

**Comment by xfguo** [comment]
链接贴到群里，我来@他们

**Comment by wsong83** [comment]
resolved by #11
