### ISSUE TITLE
0817週報內容整理

### ISSUE THREAD

**Issue by poweihuang17** [cnrv/home#14]
- [x] Apache Mynewt on Hifive @poweihuang17
- [x] Coreboot on Hifive, assigned to @citypw 
- [x] Invite Kito to introduce RV32E for riscv-gcc, assigned to @xfguo 
- [ ] Accessing CSRs in C program (requirement for memory bariers), assigned to @poweihuang17 
- [x] Major release from PULPino, assigned to @wsong83
- [x] riscv-fpu, @wangkui0508 
- [x] ORConf
- [x] Palmer的blog @poweihuang17
- [x] BOOM v2 @ wsong83 
- [x] Israel的risc-v計畫 @poweihuang17

comments:
雖然這有點幫sifive打廣告的嫌疑，但我在想任何關於software ecosystem的消息應該還是不錯的。
看到新的我會加進來。

**Comment by wsong83** [comment]
乍一眼看ECO我还以为是ASIC ECO (Engineering Change Order)，那个可不是好东西:-)

@xfguo 要不要联系Shawn让他组织一个coreboot的小专题。他是不是对它搞了加固？

**Comment by poweihuang17** [comment]
Sodor updated

**Comment by wsong83** [comment]
already added.  :-)
@poweihuang17 , maybe you can add this repo into your watch list (press the watch button).
Then you will receive an email every time there is a new PR or changes to any PR.

**Comment by poweihuang17** [comment]
OK. Sorry.

**Comment by poweihuang17** [comment]
已watch。還有一個是palmer的專欄

**Comment by poweihuang17** [comment]
然後CSR in C可能也可以寫個，我應該可以負責寫個。

**Comment by wsong83** [comment]
那CSR in C就给你了。其实在C里嵌汇编操作CSR这是基本做法，一直都是这样的。我更关心的是关于用volatile假设in-order execution的问题。参见https://groups.google.com/a/groups.riscv.org/forum/#!msg/sw-dev/TLKm-64CB-c/ieEhVUeTAwAJ
另外我也很想知道Palmer在assembly加上"memory"有什么用。
https://groups.google.com/a/groups.riscv.org/forum/#!msg/sw-dev/TLKm-64CB-c/b_2Pv0mUAwAJ

**Comment by poweihuang17** [comment]
好的。Pulpino也可以加，它更新和release了。

**Comment by poweihuang17** [comment]
在risc-v@Taiwan中出現的一個話題時，在沒有cache instruction的狀態下，怎麼產生cache invalidate的效果。譬如跟外部device共用時，該怎麼cache invalidate舊資料，在DMA前。
我記得有一些能用現有的方式達到的方法，如果能整理個表應該不錯。

**Comment by poweihuang17** [comment]
Just a record, RV32E toolchain might be good.

**Comment by wsong83** [comment]
@poweihuang17 I am going to edit your first post to make it a TODO list

**Comment by poweihuang17** [comment]
ok. thanks

**Comment by poweihuang17** [comment]
hi, @wsong83 @xfguo 
你們覺得我們把RV32E 和coreboot放在代碼更新還是新聞的區塊比較好？
我是在想跟Eco-system 擴展有關的，要不要就放在新聞？然後報導過的就放在代碼更新，除非像Pulpino一樣有重大改版，才放在新聞。

**Comment by wsong83** [comment]
我其实prefer放在新闻里，但是两个作者都很低调地选择了代码更新
😂

**Comment by poweihuang17** [comment]
嗯嗯那就按照他們的意思吧。
對了，關於Palmer的那個部落格，我提議可以新增一個區域叫實用資料。然後把文檔那類的都放在那。

**Comment by wsong83** [comment]
就在你写这个同时，我把他们挪到新闻了，额

**Comment by poweihuang17** [comment]
沒關係，就先按照你那樣吧，下次再看看要不要新增。

**Comment by wsong83** [comment]
可以呀，你也可以把我的https://github.com/cnrv/riscv-notes加上

**Comment by poweihuang17** [comment]
這次內容好多，社群大爆發嗎

**Comment by wsong83** [comment]
啊？那我可以休息了啊哈哈

**Comment by poweihuang17** [comment]
哈哈。辛苦你了。可是這次真的內容特多啊，我是指更新的方面。

**Comment by poweihuang17** [comment]
BOOM有v2了？

**Comment by wsong83** [comment]
https://groups.google.com/forum/#!topic/riscv-boom/OWCkSAeb9lQ

**Comment by wsong83** [comment]
rocket-chip PR 955 实在是看不过去了，忍不住在简报上吐槽了一把

**Comment by poweihuang17** [comment]
結果看了一下其實是Apache Mynewt被加在HiFive1上，而不是FreeRTOS。不知哪裡眼殘了。

**Comment by wsong83** [comment]
finished by #12
