### ISSUE TITLE
关于《SiFive TileLink规格书1.7.1(草案) 的中文翻译》的一些错误

### ISSUE THREAD

**Issue by LoveZJT** [cnrv/home#147]
在《SiFive TileLink规格书1.7.1(草案) 的中文翻译》，章节6.2.5 带数据确认(AccessAckData)中

> AccessAckData是一个向原请求代理返回数据的确认消息。表6.5展示了此消息在通道D
中的编码。

这里应该是 `表6.6` 。

> d_size 包括了访问的数据的尺寸，尽管这条消息本身不包含任何数据。在一个请求和
响应消息对中，d_size和a_size必须对应配置。在TL-UL中，d_size不能大于实际数据总线
的物理宽度。

`AccessAckData` 应该是带数据的。

**Comment by wsong83** [comment]
能直接发个PR吗？

**Comment by LoveZJT** [comment]
这个repo好像没有《SiFive TileLink规格书1.7.1(草案) 的中文翻译》的markdown或者latex之类的文件。

**Comment by wsong83** [comment]
啊，的确是。好吧，那交给我吧。只不过会很慢。多谢。

**Comment by wsong83** [comment]
Done via 5f01e141fc7093ebab4b4273ad23d77d90786576
