### ISSUE TITLE
分享一些新手問我的RISC-V問題

### ISSUE THREAD

**Issue by poweihuang17** [cnrv/home#25]
我在這裡貼上一些別人一開始聽到RISC-V時，會問我的問題。有興趣的，也許我們可以慢慢整理
1. MTK面試時： RISC-V 跟ARM有哪些差異？

**Comment by wsong83** [comment]
也许你可以搞一个中文FAQ页面

**Comment by NonerKao** [comment]
我曾在RISC-V很草創期的時候，
在jserv的一個演講會後問他，
「RISC-V有什麼優勢？」

結果他這樣回答：
「你念清大有什麼優勢？每件事情都要追求優勢的話，應該要去北京清華不是嗎？」

博君一笑XD

**Comment by poweihuang17** [comment]
@NonerKao Jserv大師講話常常有點難懂。

**Comment by poweihuang17** [comment]
@wsong83 我是感覺FAQ要寫的問題有點廣。我自己在資料整理這塊，是對於介紹RISC-V Instruction有興趣。但我的了解度還沒有厲害到能寫中文書。所以是先從拍小短片開始。（https://www.youtube.com/watch?v=UPHEkz_rHTY&t=2s）

**Comment by poweihuang17** [comment]
我先把這個close吧。我這邊有慢慢在整理一些常被問的問題，之後再直接加個頁面吧。
