### ISSUE TITLE
HTTPS out of sync with GitHub

### ISSUE THREAD

**Issue by wsong83** [cnrv/home#31]
现在在GitHub上的修改不能直接被推送到[https://cnrv.io](https://cnrv.io)，这导致网页内容滞后，需要手动更新。
能否有什么办法让网页自动根据GitHub更新，即使是每天同步一次也要比现在手动的好。
如果可能，也许也用ci-travis的办法？

**Comment by brchiu** [comment]
git 有所謂 hook ，是否可以使用 `post-receive` hook 來處理手動更新的動作？

[Git Hooks 7.3 Git 客製化 - Git Hooks](https://git-scm.com/book/zh-tw/v1/Git-%E5%AE%A2%E8%A3%BD%E5%8C%96-Git-Hooks)
```
post-receive 掛鉤在整個過程完結以後執行，可以用來更新其他系統服務或者通知使用者。
```

**Comment by wsong83** [comment]
好主意，不过我不会弄。大概看了看，感觉还是挺复杂的。cnrv.io的CDN是郭雄飞弄的，他应该知道具体怎么搞。看起来有些网络服务已经在提供这样的功能。比如：
https://github.com/scriptburn/git-auto-deploy
https://www.netlify.com/
http://www.wpbeginner.com/wp-themes/how-to-automatically-deploy-wordpress-theme-changes-using-github-and-dploy-io/
https://deploybot.com/
仅供参考。
