### ISSUE TITLE
現在有哪些risc-v IDE？

### ISSUE THREAD

**Issue by poweihuang17** [cnrv/home#33]
最近在教朋友risc-v programming, 你們有知道什麼好的IDE嗎？我現在只知道Sifive 的， GNU MCU Elipse，和Microsemi的windows IDE。你們都用哪個？有推薦嗎？

**Comment by wsong83** [comment]
额，我能说我不用IDE吗。Emacs+command-line。你说的三个是不是都是Eclipse扩展的。

**Comment by poweihuang17** [comment]
嗯嗯，其實我也是都用command-line，但不少人還是會想用IDE。是啊，都是Eclipse擴展的。沒關係，我研究過再update。

**Comment by poweihuang17** [comment]
這個也先close了，反正也就三個。之後要整理IDE再一起放。其實我是感覺，真的要整理，能整理的東西太多了，要整理有價值，有難度的。譬如介紹RISC-V ISA這種。有哪幾種IDE，其實很好找，隨便問一下就有，就不用特別整理了。
