### ISSUE TITLE
在週報新增“新聞報導”這個欄位？

### ISSUE THREAD

**Issue by poweihuang17** [cnrv/home#59]
剛剛重新看了一下，感覺 02-01 裡 “关于RISC-V ISA的11个谬论” 和 “走在芯片“时尚前沿”的Nvidia和西部数据” 這兩個放在 “實用資料這個欄位好像有點怪。
實用資料原本是想要放文檔、ppt等跟技術有關的學習資料。我在想，“走在芯片“时尚前沿”的Nvidia和西部数据” 這個放在”行業視角“也許比較好。但是，“关于RISC-V ISA的11个谬论” ，我就真的不知能放在哪了，以原本的分類。
還是要增加新聞報導？

**Comment by poweihuang17** [comment]
或是也可以擴大實用資料的範圍，變成把科普文章也放進去。我是感覺“关于RISC-V ISA的11个谬论”這篇，ted寫的只能算是科普，以技術上來說，不太實用 ，算是行銷。

**Comment by wsong83** [comment]
周报本身就是新闻报道，结果还要多一个新闻报道栏目？  :-)
我觉得我们可以有一个万金油（就是什么都可以的意思）栏目，叫做“其他新闻”，如何？  ：-）
