### ISSUE TITLE
Bi-weekly:要把暴走事件一直留著嗎？

### ISSUE THREAD

**Issue by poweihuang17** [cnrv/home#6]
hi @wsong83   and @xfguo,
我加上了rv8,RISCY Business, 然後merge了Shawn寫的linux port部分。
同時加上了Andes的新聞，並把SiFive和Andes的新聞都移到了市場相關。也把Shawn的安全相關移到前面跟其他技術類的放在一起。
等下我會在技術討論那裡加上cache instruction的部分。
加完之後，感覺就差不多了。
不過有個問題，我們要把暴走事件裡的內容一直留著嗎？

**Comment by poweihuang17** [comment]
我剛剛把cache instruction加完了。cache instruction在郵件中的表格在markdown中很難貼上。所以就先擺一句而已。我打算加的部分差不多了。

**Comment by wsong83** [comment]
我个人觉得可以留着成为一个固定项目。这样未来的会议什么的很容易找到，而不用回去找以前的简报。

**Comment by poweihuang17** [comment]
好，有道理。那就這樣吧～我的部分差不多了。I'll close this issue。
