### ISSUE TITLE
index the content of bi-weekly news

### ISSUE THREAD

**Issue by wsong83** [cnrv/home#92]
There are many useful knowledge points being reported in the bi-weekly news report. However, I found it difficult to find out where are those points by just looking at the titles. There should be an index to index the knowledge points; therefore, provide a good tracking of everything.

**Comment by xfguo** [comment]
@wsong83 let's upgrade the full website in one month, say before August 1st.

**Comment by wsong83** [comment]
I think this would not be finished after all. For the partially indexed weeklies, they can be accessed here: https://cnrv.io/bi-week-rpts/bi-week-rpts-index
Close.
